### ISSUE TITLE
feat: logrotate 分割・圧縮機能

### ISSUE THREAD

**Issue by Potato1682** [P2P-Develop/ServerTemplate.py#1]
# 概要

ファイルサイズが一定量に達した際に、ファイルを特定の名前フォーマットに合わせて分割する機能。

## 条件

ファイルを保存していて、分割の設定を有効にしている場合。

## 分割

%をプレフィックスとして以下のフォーマットを適用する。
- `%%` - %という文字
- `%n` - 分割数。分割インデックス。
- `%{YY-mm-dd}` - [YyMmDd]のフォーマット。

例えば、最初の分割が行われた場合に`file.1.log`としたい場合:
```
file.%n.log
```
としてトークンを置き換えることで実現できるようにする。

## 圧縮

Pythonの機能やzstdを使用して、さまざまな圧縮方式で圧縮ができるようにする。

### 種類

- `gzip` - GZip圧縮、分割ファイルのフォーマットを指定していない場合に`.gz`拡張子を末尾に追加する。
- `zstd` - ZStandard圧縮、分割ファイルのフォーマットを指定していない場合に`.zst`拡張子を末尾に追加する。
- `zip`または`deflate` - Zip圧縮、分割ファイルのフォーマットを指定していない場合に`.zip`拡張子を末尾に追加する。

### プロパティー

圧縮タイプ共通で使用できる設定を行う。
圧縮レベルなど。
圧縮タイプで指定されている圧縮レベルの範囲から外れている場合にエラーをスローする。

## ナンバリング

基本ファイル名ベース。%nが存在するファイルの%nより新しい場合、存在するファイル名の%YY-mm-ddが今より古い場合、など。

%nは基本的に問題はないと思うが、%YY-mm-ddで問題が発生するフォーマットを識別する場合%nの存在の確認が安全と考えている。
もし存在しなかった場合は`error_on_duplicate`のような設定がTrueの場合にエラー、そうでない場合は拡張子の前に` (1)`のようなものを付与する。

拡張子の識別は最初のドットより後を対象とする。

**Comment by PeyaPeyaPeyang** [comment]
既に実装されています。
