### ISSUE TITLE
feat: ログレベルを整理する

### ISSUE THREAD

**Issue by Potato1682** [P2P-Develop/ServerTemplate.py#3]
- INFO
- WARN (WARNING)
- ERROR
- FATAL
- HINT
これらでほぼ制御できる。
別のログレベルを使ってきている場合はこの中のどれかに変換。

**Comment by PeyaPeyaPeyang** [comment]
実装されています。

**Comment by Potato1682** [comment]
ログレベルが余計に多すぎると言っています。
コード内の余計なレベルを撤廃するべきです。

**Comment by PeyaPeyaPeyang** [comment]
このログレベルはslf4j氏のロガーをpythonで最低限再現しています。したがって、ログレベルはこのままにいたします。
ログレベル`HINT`は実装を検討します。

**Comment by Potato1682** [comment]
なぜ参考にしているのですか？最低限のログレベルのみ用意することでカスタマイズしやすくなると思うんですが...
